spring:
  application:
    name: daily-board
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  #  main:
  #    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 512KB
  datasource:
    url: jdbc:mysql://localhost:3306/daily-board?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes&jdbcCompliantTruncation=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'
    username: root
    password: Kuba1234*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
