/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteDuty } from '../fn/duty-controller/delete-duty';
import { DeleteDuty$Params } from '../fn/duty-controller/delete-duty';
import { DutyDto } from '../models/duty-dto';
import { getDutiesByPlannerId } from '../fn/duty-controller/get-duties-by-planner-id';
import { GetDutiesByPlannerId$Params } from '../fn/duty-controller/get-duties-by-planner-id';
import { getDutiesByPlannerIdAndRangeTime } from '../fn/duty-controller/get-duties-by-planner-id-and-range-time';
import { GetDutiesByPlannerIdAndRangeTime$Params } from '../fn/duty-controller/get-duties-by-planner-id-and-range-time';
import { getDutiesWithoutDates } from '../fn/duty-controller/get-duties-without-dates';
import { GetDutiesWithoutDates$Params } from '../fn/duty-controller/get-duties-without-dates';
import { saveDuty } from '../fn/duty-controller/save-duty';
import { SaveDuty$Params } from '../fn/duty-controller/save-duty';
import { updateDuty } from '../fn/duty-controller/update-duty';
import { UpdateDuty$Params } from '../fn/duty-controller/update-duty';

@Injectable({ providedIn: 'root' })
export class DutyControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateDuty()` */
  static readonly UpdateDutyPath = '/api/v1/duties/{plannerId}/{dutyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDuty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDuty$Response(params: UpdateDuty$Params, context?: HttpContext): Observable<StrictHttpResponse<DutyDto>> {
    return updateDuty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDuty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDuty(params: UpdateDuty$Params, context?: HttpContext): Observable<DutyDto> {
    return this.updateDuty$Response(params, context).pipe(
      map((r: StrictHttpResponse<DutyDto>): DutyDto => r.body)
    );
  }

  /** Path part for operation `deleteDuty()` */
  static readonly DeleteDutyPath = '/api/v1/duties/{plannerId}/{dutyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDuty()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDuty$Response(params: DeleteDuty$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteDuty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDuty$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDuty(params: DeleteDuty$Params, context?: HttpContext): Observable<void> {
    return this.deleteDuty$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getDutiesByPlannerId()` */
  static readonly GetDutiesByPlannerIdPath = '/api/v1/duties/{plannerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDutiesByPlannerId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesByPlannerId$Response(params: GetDutiesByPlannerId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
    return getDutiesByPlannerId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDutiesByPlannerId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesByPlannerId(params: GetDutiesByPlannerId$Params, context?: HttpContext): Observable<Array<DutyDto>> {
    return this.getDutiesByPlannerId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DutyDto>>): Array<DutyDto> => r.body)
    );
  }

  /** Path part for operation `saveDuty()` */
  static readonly SaveDutyPath = '/api/v1/duties/{plannerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveDuty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveDuty$Response(params: SaveDuty$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
    return saveDuty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveDuty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveDuty(params: SaveDuty$Params, context?: HttpContext): Observable<Array<DutyDto>> {
    return this.saveDuty$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DutyDto>>): Array<DutyDto> => r.body)
    );
  }

  /** Path part for operation `getDutiesByPlannerIdAndRangeTime()` */
  static readonly GetDutiesByPlannerIdAndRangeTimePath = '/api/v1/duties/dynamic/{plannerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDutiesByPlannerIdAndRangeTime()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesByPlannerIdAndRangeTime$Response(params: GetDutiesByPlannerIdAndRangeTime$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
    return getDutiesByPlannerIdAndRangeTime(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDutiesByPlannerIdAndRangeTime$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesByPlannerIdAndRangeTime(params: GetDutiesByPlannerIdAndRangeTime$Params, context?: HttpContext): Observable<Array<DutyDto>> {
    return this.getDutiesByPlannerIdAndRangeTime$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DutyDto>>): Array<DutyDto> => r.body)
    );
  }

  /** Path part for operation `getDutiesWithoutDates()` */
  static readonly GetDutiesWithoutDatesPath = '/api/v1/duties/constant';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDutiesWithoutDates()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesWithoutDates$Response(params?: GetDutiesWithoutDates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
    return getDutiesWithoutDates(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDutiesWithoutDates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDutiesWithoutDates(params?: GetDutiesWithoutDates$Params, context?: HttpContext): Observable<Array<DutyDto>> {
    return this.getDutiesWithoutDates$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DutyDto>>): Array<DutyDto> => r.body)
    );
  }

}
