/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface DutyDto {
  description?: string;
  effectiveDate?: string;
  effectiveTime?: LocalTime;
  from?: string;
  id?: string;
  name?: string;
  to?: string;
}
