/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface DutyDto {
  description?: string;
  effectiveDate?: string;
  from?: LocalTime;
  id?: string;
  name?: string;
  to?: LocalTime;
}
