/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DutyDto {
  color?: string;
  description?: string;
  effectiveDate?: string;
  from?: string;
  id?: string;
  name?: string;
  plannerId?: string;
  to?: string;
  weekDay?: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
}
