/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlannerDto {
  id?: string;
  isConstant?: boolean;
  title?: string;
  untilTime?: string;
}
