/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlannerDto {
  endTime?: string;
  id?: string;
  isConstant?: boolean;
  name?: string;
  note?: string;
  startTime?: string;
}
