/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DutyDto } from '../../models/duty-dto';

export interface GetDutiesByPlannerIdAndRangeTime$Params {
  plannerId: string;
  from: string;
  to: string;
}

export function getDutiesByPlannerIdAndRangeTime(http: HttpClient, rootUrl: string, params: GetDutiesByPlannerIdAndRangeTime$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
  const rb = new RequestBuilder(rootUrl, getDutiesByPlannerIdAndRangeTime.PATH, 'get');
  if (params) {
    rb.path('plannerId', params.plannerId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DutyDto>>;
    })
  );
}

getDutiesByPlannerIdAndRangeTime.PATH = '/api/v1/duties/dynamic/{plannerId}';
