/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DutyDto } from '../../models/duty-dto';

export interface GetDutiesByPlannerId$Params {
  plannerId: string;
}

export function getDutiesByPlannerId(http: HttpClient, rootUrl: string, params: GetDutiesByPlannerId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DutyDto>>> {
  const rb = new RequestBuilder(rootUrl, getDutiesByPlannerId.PATH, 'get');
  if (params) {
    rb.path('plannerId', params.plannerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DutyDto>>;
    })
  );
}

getDutiesByPlannerId.PATH = '/api/v1/duties/{plannerId}';
