/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DutyDto } from '../../models/duty-dto';

export interface UpdateDuty$Params {
  plannerId: string;
  dutyId: string;
      body: DutyDto
}

export function updateDuty(http: HttpClient, rootUrl: string, params: UpdateDuty$Params, context?: HttpContext): Observable<StrictHttpResponse<DutyDto>> {
  const rb = new RequestBuilder(rootUrl, updateDuty.PATH, 'put');
  if (params) {
    rb.path('plannerId', params.plannerId, {});
    rb.path('dutyId', params.dutyId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DutyDto>;
    })
  );
}

updateDuty.PATH = '/api/v1/duties/{plannerId}/{dutyId}';
