/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlannerDto } from '../../models/planner-dto';
import { PlannerUpdateDto } from '../../models/planner-update-dto';

export interface UpdatePlanner$Params {
  id: string;
      body: PlannerUpdateDto
}

export function updatePlanner(http: HttpClient, rootUrl: string, params: UpdatePlanner$Params, context?: HttpContext): Observable<StrictHttpResponse<PlannerDto>> {
  const rb = new RequestBuilder(rootUrl, updatePlanner.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlannerDto>;
    })
  );
}

updatePlanner.PATH = '/api/v1/planners/{id}';
